version: '3.9'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: container_nginx
    ports:
      - "2000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - php
    networks:
      - laravel

  db:
    image: postgres:14
    container_name: container_db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: aula
    ports:
      - "5433:5432"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_php
    volumes:
      - .:/var/www/html
    ports:
      - "9004:9004"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: container_composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_artisan
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
